name: Deployment Workflow

on: workflow_dispatch

jobs:
  kpi-deployment-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #   - name: Setup GitHub CLI
    #     uses: cli/cli/setup-gh@v1

      - name: Create and Update Deployment
        uses: bahag-gabelm/deploymentt@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team-short-name: ops