name: Deployment Workflow

on: workflow_dispatch

jobs:
  kpi-deployment-count:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create and Update Deployment
        uses: bahag-gabelm/deployment@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          team-short-name: ops